apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: chatapp
type: Opaque
stringData:
  JWT_SECRET: sarcasm
  MONGODB_URI: mongodb://root:Wasay120706@mongodb:27017/auth?authSource=admin

