apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pods
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: wasay786/chatapp-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production